name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd takoyaki
          ./gradlew build

  lint:
    name: Run checkstyle linter
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd takoyaki
          ./gradlew check